export enum StatusDemanda{
    BACKLOG_CLASSIFICACAO = "BACKLOG_CLASSIFICACAO",
    BACKLOG_PROPOSTA = "BACKLOG_PROPOSTA",
    BACKLOG_APROVACAO = "BACKLOG_APROVACAO",
    ASSESSMENT = "ASSESSMENT",
    BUSINESS_CASE = "BUSINESS_CASE",
    TO_DO = "TO_DO",
    DESIGN_AND_BUILD = "DESIGN_AND_BUILD",
    SUPPORT = "SUPPORT",
    CANCELLED = "CANCELLED",
    DONE = "DONE",
    DRAFT = "DRAFT"
}
