export enum StatusDemanda{
    BACKLOG_CLASSIFICACAO = "BACKLOG_CLASSIFICACAO",//0
    BACKLOG_PROPOSTA = "BACKLOG_PROPOSTA",//1
    BACKLOG_APROVACAO = "BACKLOG_APROVACAO",//2
    ASSESSMENT = "ASSESSMENT",//3
    BUSINESS_CASE = "BUSINESS_CASE",
    DISCUSSION = "DISCUSSION",
    TO_DO = "TO_DO",
    DESIGN_AND_BUILD = "DESIGN_AND_BUILD",
    SUPPORT = "SUPPORT",
    CANCELLED = "CANCELLED",
    DONE = "DONE",
    DRAFT = "DRAFT"
}
