import { Demanda } from '../models/demanda.model';
import { StatusDemanda } from "src/app/models/statusDemanda.enum";

export const listaDemandas: Demanda[] = [
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, 
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_APROVACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    ppmDemanda: "PPM 123456",
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_PROPOSTA,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.CANCELLED,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
    ppmDemanda: "PPM 123456",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    ppmDemanda: "PPM 123456",
    statusDemanda: StatusDemanda.TO_DO,
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BUSINESS_CASE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DONE,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.SUPPORT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },
  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },{
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.BACKLOG_CLASSIFICACAO,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  }, {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.ASSESSMENT,
    departamentoBenDemanda: "Tecnologia da Informação",
    ppmDemanda: "PPM 123456",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },  {
    autorDemanda: "Sabrina Hegmann",
    scoreDemanda: 2034,
    statusDemanda: StatusDemanda.DESIGN_AND_BUILD,
    ppmDemanda: "PPM 123456",
    departamentoBenDemanda: "Tecnologia da Informação",
    tituloDemanda: "Sistema de Gestão de Demandas",
  },

]
